#server
server:
  port: 10000

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  #Redis
  session:
    store-type: redis

  #naver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: MikyiaH7XQCJmKsKPMYQ
            client-secret: hsqzTHjVuV
            redirect-uri: http://localhost:10000/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,mobile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response